- udica/policy.py
In load_policy(), when the '-l' option is not set, working directory is
not restored back after setting it to TEMPLATES_STORE. Fix this by
calling chdir().
> Restore working directory

- README.md
- tests/selinux.py
- tests/semanage.py
- tests/test_main.py
Previously, the tests needed to be run on SELinux enabled system as root. Mock selinux and semanage modules so that the tests can be run anywhere and without root permissions. Also override TEMPLATES_STORE and update README.
Tested on a Ubuntu container.
>  Create mock selinux and semanage modules

- tests/semanage.py
- udica/policy.py
Resolves: #16
Previously, udica crashed when it tried to generate allow rule for some
port which is inside some range. This commit fixing the issue.
e.g: podman run -p 8612 fedora bash | udica my_testcon
Traceback (most recent call last):
File "/usr/bin/udica", line 11, in
load_entry_point('udica==0.1.4', 'console_scripts', 'udica')()
File "/usr/lib/python3.7/site-packages/udica/main.py", line 107, in main
create_policy(opts, container_caps, container_mounts, container_ports)
File "/usr/lib/python3.7/site-packages/udica/policy.py", line 118, in create_policy
policy.write(' (allow process ' + list_ports(item['hostPort']) + ' ( ' + perms.socket[item['protocol']] + ' ( name_bind ))) \n')
TypeError: can only concatenate str (not "NoneType") to str
With this fix, udica will choose right port …
> Support port ranges

- udica/templates/base_container.cil
Podman version 1.2.0 requires new allow rules.
Fixes:
type=AVC msg=audit(1556617434.540:447): avc:  denied  { create } for  pid=4692 comm="runc:[2:INIT]" scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:my_container.process:s0:c157,c366 tclass=key permissive=1
type=AVC msg=audit(1556617434.541:448): avc:  denied  { search } for  pid=4692 comm="runc:[2:INIT]" scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:my_container.process:s0:c157,c366 tclass=key permissive=1
type=AVC msg=audit(1556617434.541:449): avc:  denied  { view } for  pid=4692 comm="runc:[2:INIT]" scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:my_container.process:s0:c157,c366 tclass=key permissive=1
type=AVC …
> Add allow rules for container_runtime_t to base_container.cil

- tests/test_main.py
To simplify udica testing on Fedora, add an option that allows running the tests with real system packages (selinux and semanage). This change does not affect Travis CI (this option is turned off by default).
>  Add an option for running tests with real modules

- tests/test_main.py
Previously, due to bug in load_policy(), the current working directory
was not properly reset and the tests had to reset it. The issue was
fixed in ffbe67245b99e7b1357dd3940b6ccd166abfc096, so the tests does not
need to reset it anymore.
> Do not reset CWD in tests

- tests/selinux.py
- tests/test_main.py
- tests/test_nocontext.podman.cil
- tests/test_nocontext.podman.json
- udica/policy.py
Previously, when SELinux context was not defined in SELinux context
database, like in example below, udica crashed when tried to get context
of such a directory.
This commit fixes the issue by using selinux.getfilecon to get SELinux
context of such a file from extended attributes of the filesystem.
Fixes: #26
```
#matchpathcon /tmp/test
/tmp/test	<<none>>
Traceback (most recent call last):
File "/bin/udica", line 11, in <module>
load_entry_point('udica==0.1.7', 'console_scripts', 'udica')()
File "/usr/lib/python3.7/site-packages/udica/__main__.py", line 109, in main
create_policy(opts, container_caps, container_mounts, container_ports)
File "/usr/lib/python3.7/site-packages/udica/policy.py", line 173, in create_policy
contexts = list_contexts(item['source'])
File …
```
> Get SELinux context of mountpoint from xattr

- tests/test_main.py
Split large helper function into several smaller ones. Move reloading of
modules and setup tasks to setUp() function. Create run_udica() function
for running udica and recording its output. Create assert_templates()
function for checking generated templates. Create assert_policy()
function for comparing generated policy with a file. Create
assert_ansible() function for checking files generated for ansible.
> Clean up the test helper

- udica/__main__.py
- udica/man/man8/udica.8
- udica/parse.py
- udica/policy.py
Return 3 on container-related issues, 4 on SELinux related issues.
Return 2 when supplied invalid options and 1 on other errors. Update man
page.
> Unify exit codes

- tests/test_main.py
- tests/test_stream_connect.podman.cil
- udica/__main__.py
- udica/man/man8/udica.8
- udica/policy.py
- udica/templates/base_container.cil
This feature allows specify container communication using stream sockets.
Communication is specified via new parameter "--stream-connect".
Feature example:
Create containerA:
Create containerB which could stream connect to containerA:
Now, containerB contains following additional rules and communicate with
containerA via stream socket:
allow containerB.process containerA.process:unix_stream_socket connectto;
allow containerB.process containerA.socket ( sock_file ( getattr write open append )))
This feature also add new object to base container template for creating
socket file under every container namespace. e.g: my_container.socket,
network_container.socket.
> New feature: Cross Container Communication

- udica/templates/log_container.cil
For the log_rw_container it wasn't possible to create new files, which
is something that's normally required. So we're adding this
capability, while still not allowing that container to rename that
directory or remove files from it as a security measure.
The audit_log_t file was also modified to be more restrictive for the
log_rw_container block, so we only allow reads now. However, the write
capability was left for the log_manage_container block.
> Improve permission set for log_container template

- tests/test_basic.cri.json
- udica/__main__.py
- udica/parse.py
- udica/policy.py
This takes modifies udica to also take the "inspect" format that crictl
gives out, and not only the docker/podman one.
Note that in this implementation, only the json file works; support for
parsing the input from the crictl command will come in a separate PR.
> Initial CRI-O support

- udica/policy.py
Some of the imports in udica/policy.py weren't used. This cleans them
up.
Closes: #41
> udica/policy.py: Remove unused imports

- .travis.yml
- Makefile
- README.md
- tests/test_integration.py
- tests/test_main.py
- tests/test_unit.py
This creates a very basic Makefile and refactors the tests so they can be ran from the top level directory.
The tests have also been separated into unit tests and integration tests.
The unit tests are what is still being ran on CI, and is what's called from the "test" target in the makefile.
The integration tests can be called directly from the module. e.g. `python3 tests/test_integration.py`, and this will actually require the python SELinux packages to be installed, as well as the udica python package itself (given that we would be testing integration). Currently it runs the same tests as the unit tests, but it can be extended in the future.
> Create Makefile and refactor tests

- Dockerfile
- Makefile
- README.md
This adds a dockerfile which allows you to build a container for udica
from source.
It also includes a Makefile that'll allow you to build the image with
your preferred command (the default is podman and the default tag is
"latest").
Note that in ordre to use udica as a container, you need to bind-mount
the following directories to it:
* /sys/fs/selinux
* /etc/selinux
* /var/lib/selinux
> Add Dockerfile for udica container

- .travis.yml
- Makefile
- udica/__main__.py
This adds a lint target to the makefile. This target runs pyflakes on the udica package.
It was also added to CI.
> Add lint target

- udica/templates/base_container.cil
`container.process` is currently not mcs-constrained, and so by default, types that inherit container.process are not either.
It is important for such types to enforce that resources with different categories (i.e. pods) won't be able to interact with each other by default.
This PR fixes that.
> Make container types mcs-constrained

- setup.py
- udica/parse.py
Prevent Udica instalation under py2 as py3-only is supported.
Signed-off-by: Martin Bašti <mbasti@redhat.com>
> Specify required python version

- setup.py
- udica/parse.py
EngineHelper is an abstract class and should be treated like abstract class using python stdlib tools
Signed-off-by: Martin Bašti <mbasti@redhat.com>
> Refactor to proper abstract class

- udica/templates/config_container.cil
- udica/templates/home_container.cil
- udica/templates/log_container.cil
- udica/templates/net_container.cil
- udica/templates/tmp_container.cil
- udica/templates/tty_container.cil
- udica/templates/virt_container.cil
- udica/templates/x_container.cil
Cil parser was recently updated to reject the following:
(block template1 (type t) )
(block template2 (blockinherit template1))
(block b (blockinherit template1) (blockinherit template2))
Re-declaration of type t
Previous declaration of type at /var/lib/selinux/targeted/tmp/modules/400/test/cil:1
Failed to copy block contents into blockinherit
Failed to resolve AST
semodule:  Failed!
Remove (blockinherit container) from all templates so that "process" and
"socket" are only defined once (by inheriting "container" block in the
generated policy).
All allow rules referencing "process" and "socket" now need to be
enclosed in an optional block.
While at it, unify indentation.
Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
> Update templates to work properly with new cil parser

- .cirrus.yml
- contrib/cirrus/build.sh
- contrib/cirrus/setup.sh
Note F35 is disabled due to golang 1.18 requirement in podman. The
PRIOR_FEDORA... runs may be put back in place when F37 is released.
Signed-off-by: Chris Evich <cevich@redhat.com>
> Cirrus: Update CI VM images

- .cirrus.yml
Cirrus: Update CI VM images to F37
Ref: https://github.com/containers/automation_images/pull/246
Also, fully remove any hit that CI will ever work on the prior-supported
Fedora release.  Doing so requires some special CNI setup in the podman
repository CI scripts.  I attempted to re-use them here (in `build.sh`)
but it was too difficult and likely would be error-prone.
> Cirrus: Update CI VM Images to F37

- .github/workflows/checks.yml
Centos8 container always fails with
Curl error (6): Couldn't resolve host name for
mirrorlist.centos.org
> github: disable testing on centos8
